# Dstack Vstack Hstack

In [ ]:
def load_file(filepath):
    dataframe = read_csv(filepath, header=None, delim_whitespace=True)
    return dataframe.values

In [ ]:
def load_group(filenames, prefix=''):
    loaded = list()
    for name in filenames:
        data = load_file(prefix + name)
        loaded.append(data)
    # stack group so that features are the 3rd dimension
    loaded = dstack(loaded)
    return loaded
files1=["Acc","LAcc","Mag","Gra","Gyr"]
files2=[]
for i in files1:
    for j in ["x","y","z"]:
        files2+=["data/"+i+"_"+j+".txt"]
pred=load_group(files2)        

In [ ]:
print(a.shape, b.shape)
# (3, 2) (3, 2)
print(np.vstack((a, b)).shape)
# (6, 2)
print(np.hstack((a, b)).shape)
# (3, 4)
print(np.dstack((a, b)).shape)
# (3, 2, 2)

In [1]:
from numpy import hstack,vstack,dstack
import numpy as np
import pandas as pd

In [15]:
a1=np.array([[[1 for k in range(0,3)]for j in range(0,3)]for i in range(0,3)])
b1=np.array([[[2 for k in range(0,3)]for j in range(0,3)]for i in range(0,3)])

In [16]:
a=np.array([[1 for j in range(0,3)]for i in range(0,3)])
b=np.array([[2 for j in range(0,3)]for i in range(0,3)])

In [17]:
a2=np.array([[[[1 for l in range(0,3)] for k in range(0,3)]for j in range(0,3)]for i in range(0,3)])
b2=np.array([[[[2 for l in range(0,3)] for k in range(0,3)]for j in range(0,3)]for i in range(0,3)])

In [13]:
a2

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

In [21]:
pd.DataFrame([[[[1 for l in range(0,3)] for k in range(0,3)]for j in range(0,3)]for i in range(0,3)])

0                                  1  \
0  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]   
1  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]   
2  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]   

                                   2  
0  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]  
1  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]  
2  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [18]:
print(vstack((a2, b2)).shape,"\n\n\n")
print(vstack((a, b)))

(6, 3, 3, 3) 



[[1 1 1]
 [1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [20]:
print(dstack((a2, b2)).shape,"\n\n\n")
print(dstack((a2, b2)))

(3, 3, 6, 3) 



[[[[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [2 2 2]
   [2 2 2]
   [2 2 2]]]]


In [19]:
print(hstack((a, b)).shape,"\n\n\n")
print(hstack((a, b)))

(3, 6, 3) 



[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [2 2 2]
  [2 2 2]
  [2 2 2]]]


# Reshape

In [ ]:
arr=arr.shape(dim1,dim2,dim3)
pred = pred.reshape((pred.shape[0], n_steps, n_length, n_features))

## Save numpy

In [ ]:
numpy.savetxt("foo.csv", a, delimiter=",")